### ISSUE TITLE
No file cppfs_api.h

### ISSUE THREAD

**Issue by vega0** [cginternals/cppfs#29]
cppfs/source/cppfs/include/cppfs/AbstractFileSystem.h:8:10: fatal error: cppfs/cppfs_api.h:

**Comment by scheibel** [comment]
Can you specify the following information?
 * Your operating system
 * Your compiler
 * Do you build cppfs from source yourself or do you try to use it as a dependency?

**Comment by pheeque** [comment]
Hi @scheibel. Currently encountering the same problem while using the header files in my project. If you check here: https://github.com/cginternals/cppfs/tree/master/source/cppfs/include/cppfs, the header file cppfs_api.h  requested from the AbstractFileSystem.h does not exist at all.

Thanks.

**Comment by scheibel** [comment]
The file is not part of the source tree as it is generated during CMake build directory creation and configuration. That's why I asked for your build setup. You need to use an actual development package (either create it from source, where CMake get's executed and the `cppfs_api.h` is generated or use a pre-build cppfs package where this file is added, too).

**Comment by OverShifted** [comment]
Hi. I wanna use this library in my game engine.
it currently builds with premake and CMake.
CMake works fine because it generates `cppfs_api.h` file + adds it to include directories.
Is there any possible way to build cppfs using premake? Has anyone done it?
Or should I drop premake support?

**Comment by sbusch42** [comment]
Hi @OverShifted. As far as I can see, premake does not seem to support anything like cmake's configure_file or generate_export_header. If you want to support it, I guess it would be easiest to just add a static API header file instead of generating it, using some ifdefs to differentiate between the platforms you want to support , e.g., windows and unix. You can find plenty of examples how such a header file should look like, for example: https://stackoverflow.com/questions/19418908/creating-a-portable-library-to-run-on-both-linux-and-windows
