### ISSUE TITLE
Build option for enabling/disabling SSH2 and Crypto(sha1)?

### ISSUE THREAD

**Issue by NearlyTRex** [cginternals/cppfs#5]
Hi,
I like the project so far, but I want to propose having some preprocessor options for enabling/disabling external library usage. For me, I'm only interested in local file operations and I end up commenting out the SHA1 calls in fs.cpp and FileHandle.cpp. It also references the SSH library too. It works fine if I exclude the ssh files from the build and comment out those references, but maybe a -DUSE_SSL2 and -DUSE_CRYPTO might help future users?
Forgive me if this is not the right format for an issue, I'm new to this.

**Comment by sbusch42** [comment]
Thank you for your suggestions.

An option for disabling the SSH backend would be fine, I think we would rather name it OPTION_USE_SSH as analog to the other options (see the main CMakeLists.txt).

The libcrypto is needed for the sha1 function, which I find helpful also for local file operations, but having an option here wouldn't hurt either, if you do not need that functionality.

Would you care preparing a pull request for this? Otherwise I don't know when I will find the time to make these changes.

**Comment by gabm** [comment]
I started working on this as well but stumbled across this branch... looks great so far, but I think the current implementation has limitations:

- each library is linked/used independently. I don't know too much about the code but I suspect that if libSSH is not available and the ssh module is not compiled, then openssl is not necessary.. is that true?
- I think there are scenarios in which libssh2 backend is available in the environment but not wanted during build. Thats why an explicit option would make sense...
